# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Njc3NjljMTg3MmJkYjUzNDlmZWMzY2VmZjMwMGQ1OGNiNDA1YTA0NmQzNTBhNmI4NTg5MjY2NDhjNGUyMzQzZjhjMDhiZmJjMzE1MzQ5MTM0NGRmYTU4NGVmNzQxMTU4ZTU0NjU1NjY2MDFjZTI2ZWZlNzhiMjI5ZDc1YzE1YTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
